name: "Tests"
on: [push, pull_request]

jobs:
  jest-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Dependencies
        run: npm ci
      - name: Test Build
        run: npm run test_build
      - name: Checking format
        if: matrix.os == 'ubuntu-latest'
        run: npm run format-check
      - name: Linting code
        if: matrix.os == 'ubuntu-latest'
        run: npm run lint
      - name: Running jest tests
        run: npm test
      - name: Codecov Upload
        continue-on-error: true
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/lcov.info

  release-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Dependencies
        run: npm ci
      - name: Create fresh build release  compare file
        run: npm run build-compare-file
      - name: Test if the release and compare file are different
        run: diff -qywBd dist/index.js compare/index.js

  test-integration:
    runs-on: ${{ matrix.os }}
    needs: [jest-tests, release-up-to-date]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm ci
      - name: Build index.js
        run: npm run build
      - uses: ./
        with:
          dummy-input: "bar"
