name: "Tests"
on: [push, pull_request]

jobs:
  jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm ci
      - name: Test Build
        run: npm run build
      - name: Checking format
        run: npm run format-check
      - name: Linting code
        run: npm run lint
      - name: Running jest tests
        run: npm test

  release-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm ci
      - name: Create fresh build release  compare file
        run: npm run release-compare-file
      - name: Test if the release and compare file are different
        run: diff -qywBd dist/index.js compare/index.js
